package com.labex.langchain4j.agent;

import lombok.Data;

/**
 * DTO for a question generated by LLM from lecture content.
 */
@Data
public class GeneratedQuestion {
    /** Question type: 1=fill-blank, 2=single-choice, 3=multi-choice, 4=judgment, 5=short-answer, 6=programming */
    private int type;
    /** Question content (may include HTML) */
    private String question;
    /** Correct answer */
    private String answer;
    /** Detailed analysis/explanation */
    private String analysis;
    /** Choice options — can be JSON string or JSON object from LLM */
    private Object options;
    /** Knowledge point label, e.g. "变量作用域" */
    private String knowledgePoint;
    /** Difficulty: "easy", "medium", or "hard" */
    private String difficulty;
    /** Score for this question */
    private Integer score;
}
