-- 修复 t_paper 表缺少的字段
ALTER TABLE t_paper
ADD COLUMN IF NOT EXISTS total_score INT DEFAULT NULL COMMENT '总分' AFTER description,
ADD COLUMN IF NOT EXISTS question_count INT DEFAULT NULL COMMENT '题目数量' AFTER total_score,
ADD COLUMN IF NOT EXISTS teacher_id INT DEFAULT NULL COMMENT '教师ID' AFTER time,
ADD COLUMN IF NOT EXISTS state INT DEFAULT 1 COMMENT '状态' AFTER teacher_id;

-- 修复 t_exam 表缺少的字段
ALTER TABLE t_exam
ADD COLUMN IF NOT EXISTS exam_name VARCHAR(100) DEFAULT NULL COMMENT '考试名称' AFTER id,
ADD COLUMN IF NOT EXISTS paper_id INT DEFAULT NULL COMMENT '试卷ID' AFTER exam_name,
ADD COLUMN IF NOT EXISTS total_score INT DEFAULT NULL COMMENT '总分' AFTER paper_id,
ADD COLUMN IF NOT EXISTS teacher_id INT DEFAULT NULL COMMENT '教师ID' AFTER total_score,
ADD COLUMN IF NOT EXISTS total_times INT DEFAULT 1 COMMENT '考试次数' AFTER teacher_id,
ADD COLUMN IF NOT EXISTS end_time DATETIME DEFAULT NULL COMMENT '结束时间' AFTER total_times,
ADD COLUMN IF NOT EXISTS state INT DEFAULT 1 COMMENT '状态' AFTER end_time;

-- 修复 t_student_question 表
ALTER TABLE t_student_question
ADD COLUMN IF NOT EXISTS exam_id INT DEFAULT NULL COMMENT '考试ID' AFTER student_id,
ADD COLUMN IF NOT EXISTS my_answer TEXT DEFAULT NULL COMMENT '学生答案' AFTER exam_id,
ADD COLUMN IF NOT EXISTS score INT DEFAULT NULL COMMENT '得分' AFTER my_answer,
ADD COLUMN IF NOT EXISTS is_correct INT DEFAULT NULL COMMENT '是否正确' AFTER score,
ADD COLUMN IF NOT EXISTS fill_time DATETIME DEFAULT NULL COMMENT '答题时间' AFTER is_correct,
ADD COLUMN IF NOT EXISTS graded TINYINT(1) DEFAULT 0 COMMENT '是否已评分' AFTER fill_time;

-- 删除原来的 answer 列（如果存在且不再使用）
-- ALTER TABLE t_student_question DROP COLUMN IF EXISTS answer;